import type { Term } from "../../app/generated/prisma/client";

/**
 * Term-by-term degree roadmap, sourced from Western's official Progression
 * Sheets (eng.uwo.ca, Sept 2026 editions -- the same documents used to audit
 * the course catalog for completeness). Only the 8 disciplines with a clean
 * standalone sequence are modelled -- AISE and Biomedical are combined
 * degrees layered on top of a base discipline, not a path of their own, so
 * they're deliberately left out rather than forced into a grid that would
 * misrepresent them.
 *
 * Year 1 is intentionally not modelled here -- it's identical across every
 * discipline (see the `first-year` Discipline), and while the *course list*
 * for it is fully verified, the exact Fall/Winter split per course isn't,
 * so it's left off rather than guessed at.
 *
 * `courseCode` is set for one fixed required course. `electiveLabel` is set
 * instead for a slot the progression sheet itself leaves open (a technical
 * elective, or an explicit choice between two named courses) -- this is
 * never a guess at which specific course fills the slot, only what the
 * sheet itself says is open. Full-year courses (no A/B split -- e.g. a "Y"
 * suffix, or a lab course spanning both terms per its own description) are
 * listed once, in the Fall slot, rather than duplicated in both terms.
 */
export type ProgressionSlotSeed = {
  yearLevel: number;
  term: Term;
  sortOrder: number;
  courseCode?: string;
  electiveLabel?: string;
};

export const PROGRESSION: Record<string, ProgressionSlotSeed[]> = {
  electrical: [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "CS 1027A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "ECE 2205A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "ECE 2277A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "ECE 2240A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "WRIT 2130F/G" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "ECE 2231A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "ECE 2233A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "ECE 2236A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "ECE 2242A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "NMM 3415A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "ECE 3330A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "ECE 3332A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "ECE 3337A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "SS 2141A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "ECE 3331A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "ECE 3333A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "ECE 3336A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "ECE 3375A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "ECE 3399A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "ECE 4416" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "ECE 4429A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "ECE 4437A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 3, electiveLabel: "Technical elective(s)" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "ELI 4110F/G" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, electiveLabel: "Technical elective(s)" },
  ],
  software: [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "ECE 2277A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "SE 2202A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "SE 2205A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "MATH 2151A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "SS 2141A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "PHYS 2300A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "SE 2203A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "SE 2250A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "WRIT 2130F/G" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "ECE 4436A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "SE 3309A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "SE 3351A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "SE 3316A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "SE 3352A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 5, courseCode: "SE 3310A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "ECE 3375A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "SE 3313A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "SE 3353A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "SE 3350A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "SE 4450" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "SE 4452A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "SE 4472A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "SE 4450" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "SE 4455A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, courseCode: "ELI 4110F/G" },
  ],
  mechatronics: [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "MSE 2201A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "ECE 2205A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "MME 2202A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "MME 2204A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "CS 1037A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "MSE 2202A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "MSE 2221A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "MSE 2233A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "MME 2213A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 5, courseCode: "MME 2273A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "MSE 3301A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "MSE 3310A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "ECE 2277A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "ECE 3330A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "MME 3381A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "MSE 3302A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "ECE 3331A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "ECE 3375A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "MME 3360A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "MME 3380A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 5, courseCode: "WRIT 2130F/G" },
    { yearLevel: 3, term: "WINTER", sortOrder: 6, electiveLabel: "Non-technical elective" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "MSE 4401A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "MSE 4499" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "SS 2141A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 3, courseCode: "ELI 4110F/G" },
    { yearLevel: 4, term: "FALL", sortOrder: 4, electiveLabel: "Technical elective(s) (x2)" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "MSE 4499" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, electiveLabel: "ECE 4460A/B or ECE 4469A/B (choose one)" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, electiveLabel: "Non-technical elective(s) (x2)" },
    { yearLevel: 4, term: "WINTER", sortOrder: 3, electiveLabel: "Technical elective" },
  ],
  mechanical: [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "MME 2202A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "MME 2204A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "MME 2259A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "MME 2260A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "WRIT 2130F/G" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "MME 2213A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "MME 2221A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "MME 2273A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "MME 2285A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 5, courseCode: "SS 2143A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "MME 3325A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "MME 3303A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "MME 3348A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "MME 3381A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "MME 3374A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "MME 3307A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "MME 3334A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "MME 3350A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "MME 3360A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "MME 3380A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "MME 4499" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "ELI 4110F/G" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, electiveLabel: "Technical elective(s)" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "MME 4499" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, electiveLabel: "Technical elective(s)" },
  ],
  civil: [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "CEE 2225A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "CEE 2202A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "CEE 2217A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "CEE 2220A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "SS 2141A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2277A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "CEE 2226A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "CEE 2219A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "CEE 2221A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "EARTHSCI 2281A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 5, courseCode: "WRIT 2130F/G" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "CEE 3321A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "CEE 3340A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "CEE 3369A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "CEE 3347A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "CEE 3348A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "CEE 3322A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "CEE 3343A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "CEE 3346A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "CEE 3358A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "CEE 3344A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "CEE 4441" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "CEE 4426A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "CEE 4491A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "CEE 4441" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "CEE 4424A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, courseCode: "CEE 4478A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 3, courseCode: "ELI 4110F/G" },
  ],
  chemical: [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "CBE 2206A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "CBE 2214A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "CBE 2220A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "CBE 2290A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "WRIT 2130F/G" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2277A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "CBE 2207A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "CBE 2221A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "CBE 2224A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "CBE 2291A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 5, courseCode: "SS 2143A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "CBE 3307A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "CBE 3315A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "CBE 3318A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "CBE 3322A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "CBE 3395Y" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "CBE 3310A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "CBE 3316A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "CBE 3319A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "CBE 3323A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "CBE 3324A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "CBE 4497" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "CBE 4497" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "ELI 4110F/G" },
  ],
  integrated: [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "IE 2298" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "CEE 2220A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "CBE 2220A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "ECE 2277A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "MME 2204A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 6, courseCode: "IE 2200Y" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "CBE 2221A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "MME 2285A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "SS 2143A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "ELI 3000A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "CBE 3322A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "CEE 2202A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "MME 3374A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "ELI 3100A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "CEE 2221A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "MME 2213A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "CBE 2291A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "MME 3360A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "IE 4499" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "ELI 4100F/G" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "ELI 4110F/G" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "IE 4499" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, electiveLabel: "ELI elective" },
  ],
};
