import type { ProgressionSlotSeed } from "./progression";

/**
 * Term-by-term roadmap for the two combined/double-degree programs -- AISE
 * and Biomedical Engineering -- layered on top of the 4 base disciplines
 * that actually offer that combo (electrical, mechanical, mechatronics,
 * chemical; civil, software, and integrated have no AISE/BME option).
 * Sourced from Western's official combined-degree Progression Sheets
 * (eng.uwo.ca, Sept 2026 editions, Jan 2026 for MME+BME -- read directly,
 * same rigor as prisma/seed-data/progression.ts).
 *
 * Unlike the base 4-year sequences, these run 5 years and substantially
 * restructure the curriculum rather than just adding courses on top --
 * confirmed directly from all 8 combo sheets, which is why this is a
 * separate overlay dataset rather than an extension of PROGRESSION.
 *
 * Keyed by `${baseDisciplineSlug}+${overlaySlug}` (overlaySlug is "aise"
 * or "biomedical"). Same modelling rules as the base data: 0-credit safety
 * training (MSE 2200Q, MME 2200S) is skipped, "Y"-suffix full-year courses
 * are listed once in the Fall slot, and design-project/thesis courses that
 * lack an A/B or Y suffix but are explicitly listed in both Fall and
 * Winter on the source sheet (ECE 4416, MME 4499, MSE 4499, CBE 4497,
 * BME 4400E) are listed in both terms, matching how the base data already
 * treats MME 4499/CBE 4497/MSE 4499.
 *
 * A few source-sheet quirks resolved against the live course catalog
 * rather than guessed at:
 * - "MSE 3381A" (mechatronics+AISE, mechatronics+biomedical sheets) is the
 *   department's own legacy code for what the catalog lists as
 *   MME 3381A/B -- confirmed by MME 3381A/B's own antirequisite text
 *   ("the former MSE 3381A/B").
 * - "ELI 4410F" (appears on both Biomedical ECE and MME sheets) is a typo
 *   for ELI 4110F/G -- the only catalog course with that exact title
 *   ("Engineering Ethics, Sustainable Development & the Law"), and every
 *   other combo sheet spells it correctly.
 * - The Year 5 Term B "ELI 3100A or ELI 3000A or ELI 4200B or ELI 4300A/B
 *   or ELI 4400A/B" elective block (all 4 Biomedical sheets) only has 3
 *   of those 5 codes in the catalog (ELI 3000A/B, ELI 3100A/B,
 *   ELI 4200A/B) -- ELI 4300/4400 aren't in it, so the slot is modelled
 *   as an open choice among the verified options rather than a fixed code.
 */

export const COMBINED_PROGRESSION: Record<string, ProgressionSlotSeed[]> = {
  "electrical+aise": [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "AISE 2205A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "ECE 2277A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "ECE 2240A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "ECE 2205A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "SS 2143A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "AISE 2251A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "ECE 2236A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "ECE 2233A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 5, courseCode: "WRIT 2130F/G" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "DS 3000A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "AISE 3309A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "AISE 3350A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "ECE 3330A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "ECE 3332A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 5, courseCode: "NMM 3415A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "AISE 3010A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "ECE 3331A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "ECE 3333A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "ECE 3375A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "ECE 2231A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 5, courseCode: "ECE 2242A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "AISE 4010A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "AISE 4430A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "ECE 3337A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 3, electiveLabel: "AISE technical elective" },
    { yearLevel: 4, term: "FALL", sortOrder: 4, electiveLabel: "Technical elective" },
    { yearLevel: 4, term: "FALL", sortOrder: 5, electiveLabel: "Non-technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "AISE 4020A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "ECE 3399A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, courseCode: "ECE 3336A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 3, electiveLabel: "Technical elective" },
    { yearLevel: 5, term: "FALL", sortOrder: 0, courseCode: "ECE 4416" },
    { yearLevel: 5, term: "FALL", sortOrder: 1, courseCode: "AISE 4450A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 2, courseCode: "AISE 3020A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 3, courseCode: "ECE 4437A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 4, electiveLabel: "Technical elective(s) (x2)" },
    { yearLevel: 5, term: "FALL", sortOrder: 5, electiveLabel: "AISE technical elective" },
    { yearLevel: 5, term: "WINTER", sortOrder: 0, courseCode: "ECE 4416" },
    { yearLevel: 5, term: "WINTER", sortOrder: 1, courseCode: "ELI 4110F/G" },
    { yearLevel: 5, term: "WINTER", sortOrder: 2, electiveLabel: "Technical elective(s) (x2)" },
    { yearLevel: 5, term: "WINTER", sortOrder: 3, electiveLabel: "Non-technical elective" },
  ],

  "mechanical+aise": [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "AISE 2205A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "MME 2202A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "MME 2204A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "MME 2260A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "MME 2259A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "AISE 2251A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "MME 2285A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "MME 2273A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "SS 2143A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "DS 3000A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "AISE 3309A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "AISE 3350A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "MME 3348A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "MME 3374A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 5, electiveLabel: "Non-technical elective" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "AISE 3010A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "AISE 3351A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "MME 2213A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "MME 2221A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "WRIT 2130F/G" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "AISE 4010A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "AISE 4430A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "MME 3325A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 3, courseCode: "MME 3381A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 4, courseCode: "MME 3303A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 5, electiveLabel: "AISE technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "AISE 4020A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "MME 3334A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, courseCode: "MME 3350A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 3, courseCode: "MME 3307A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 4, courseCode: "MME 3360A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 5, courseCode: "MME 3380A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 0, courseCode: "MME 4499" },
    { yearLevel: 5, term: "FALL", sortOrder: 1, courseCode: "AISE 4450A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 2, courseCode: "AISE 3020A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 3, courseCode: "ELI 4110F/G" },
    { yearLevel: 5, term: "FALL", sortOrder: 4, electiveLabel: "Technical elective" },
    { yearLevel: 5, term: "FALL", sortOrder: 5, electiveLabel: "Non-technical elective" },
    { yearLevel: 5, term: "WINTER", sortOrder: 0, courseCode: "MME 4499" },
    { yearLevel: 5, term: "WINTER", sortOrder: 1, electiveLabel: "Technical elective(s) (x2)" },
    { yearLevel: 5, term: "WINTER", sortOrder: 2, electiveLabel: "Non-technical elective" },
    { yearLevel: 5, term: "WINTER", sortOrder: 3, electiveLabel: "AISE technical elective" },
  ],

  "mechatronics+aise": [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "MME 2202A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "MME 2204A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "AISE 2205A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "SS 2141A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "MSE 2221A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "MME 2213A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "MME 2273A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "AISE 2251A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 5, electiveLabel: "Non-technical elective(s) (x2)" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "MSE 2201A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "ECE 2205A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "DS 3000A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "AISE 3309A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "AISE 3350A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 5, electiveLabel: "Non-technical elective" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "MSE 2202A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "MSE 2233A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "MME 3360A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "AISE 3010A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "AISE 3351A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 5, courseCode: "WRIT 2130F/G" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "MSE 3310A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "MME 3381A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "ECE 2277A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 3, courseCode: "ECE 3330A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 4, courseCode: "AISE 4010A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 5, courseCode: "AISE 4430A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "MSE 3302A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "ECE 3375A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, courseCode: "MME 3380A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 3, courseCode: "AISE 4020A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 4, electiveLabel: "AISE technical elective" },
    { yearLevel: 5, term: "FALL", sortOrder: 0, courseCode: "MSE 3301A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 1, courseCode: "MSE 4401A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 2, courseCode: "MSE 4499" },
    { yearLevel: 5, term: "FALL", sortOrder: 3, courseCode: "AISE 3020A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 4, courseCode: "AISE 4450A/B" },
    { yearLevel: 5, term: "WINTER", sortOrder: 0, courseCode: "MSE 4499" },
    { yearLevel: 5, term: "WINTER", sortOrder: 1, electiveLabel: "ECE 4460A/B or ECE 4469A/B (choose one)" },
    { yearLevel: 5, term: "WINTER", sortOrder: 2, courseCode: "ELI 4110F/G" },
    { yearLevel: 5, term: "WINTER", sortOrder: 3, electiveLabel: "AISE technical elective(s) (x2)" },
  ],

  "chemical+aise": [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "AISE 2205A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "CBE 2290A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "CBE 2206A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "CBE 2214A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "CBE 2220A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2277A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "AISE 2251A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "SS 2143A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "CBE 2207A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "CBE 2221A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 5, courseCode: "CBE 2224A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "DS 3000A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "AISE 3309A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "AISE 3350A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "CBE 3315A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "CBE 3322A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 5, electiveLabel: "Non-technical elective" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "AISE 3010A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "AISE 3351A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "CBE 2291A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "CBE 3323A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "CBE 3324A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 5, courseCode: "WRIT 2130F/G" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "AISE 4010A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "AISE 4430A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "CBE 3307A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 3, courseCode: "CBE 3318A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 4, courseCode: "CBE 3395Y" },
    { yearLevel: 4, term: "FALL", sortOrder: 5, electiveLabel: "Non-technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "AISE 4020A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "CBE 3310A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, courseCode: "CBE 3316A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 3, courseCode: "CBE 3319A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 4, electiveLabel: "AISE technical elective" },
    { yearLevel: 5, term: "FALL", sortOrder: 0, courseCode: "CBE 4497" },
    { yearLevel: 5, term: "FALL", sortOrder: 1, courseCode: "AISE 4450A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 2, courseCode: "AISE 3020A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 3, courseCode: "ELI 4110F/G" },
    { yearLevel: 5, term: "FALL", sortOrder: 4, electiveLabel: "Non-technical elective" },
    { yearLevel: 5, term: "WINTER", sortOrder: 0, courseCode: "CBE 4497" },
    { yearLevel: 5, term: "WINTER", sortOrder: 1, electiveLabel: "AISE technical elective" },
    { yearLevel: 5, term: "WINTER", sortOrder: 2, electiveLabel: "CBE technical elective(s) (x2)" },
  ],

  "electrical+biomedical": [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "BME 3201A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "CS 1027A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "ECE 2205A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "ECE 2240A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "ECE 2277A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "ECE 2231A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "ECE 2233A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "ECE 2236A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "ECE 2242A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 5, electiveLabel: "Non-technical elective" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "NMM 3415A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "BIOL 1001A" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "ECE 3330A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "ECE 3332A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "BME 3301A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 5, courseCode: "ECE 3337A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 6, courseCode: "SS 2141A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "BIOL 1002B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "ECE 3331A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "ECE 3336A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "ECE 3375A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "ECE 3399A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "BIOCHEM 2280A" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "ECE 4455A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "PHYSIOL 2130" },
    { yearLevel: 4, term: "FALL", sortOrder: 3, electiveLabel: "Biomedical Science elective" },
    { yearLevel: 4, term: "FALL", sortOrder: 4, electiveLabel: "Healthcare non-technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "BME 3303A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "MME 4469A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, courseCode: "ECE 3333A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 3, courseCode: "PHYSIOL 2130" },
    { yearLevel: 4, term: "WINTER", sortOrder: 4, electiveLabel: "Biomedical Science elective(s) (x2)" },
    { yearLevel: 4, term: "WINTER", sortOrder: 5, electiveLabel: "Healthcare non-technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 6, electiveLabel: "Open elective" },
    { yearLevel: 5, term: "FALL", sortOrder: 0, courseCode: "BME 4400E" },
    { yearLevel: 5, term: "FALL", sortOrder: 1, courseCode: "ECE 4416" },
    { yearLevel: 5, term: "FALL", sortOrder: 2, courseCode: "ECE 4429A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 3, courseCode: "ECE 4437A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 4, courseCode: "ECE 4445A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 5, courseCode: "ELI 4110F/G" },
    { yearLevel: 5, term: "WINTER", sortOrder: 0, courseCode: "BME 4400E" },
    { yearLevel: 5, term: "WINTER", sortOrder: 1, courseCode: "ECE 4416" },
    {
      yearLevel: 5,
      term: "WINTER",
      sortOrder: 2,
      electiveLabel: "ELI 3000A/B, ELI 3100A/B, or ELI 4200A/B (or another approved elective, choose one)",
    },
    { yearLevel: 5, term: "WINTER", sortOrder: 3, electiveLabel: "BME technical elective(s) (x2)" },
    { yearLevel: 5, term: "WINTER", sortOrder: 4, electiveLabel: "ECE technical elective" },
  ],

  "mechanical+biomedical": [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "BME 3201A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "MME 2202A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "MME 2204A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "MME 2259A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "MME 2260A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "MME 2221A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "MME 2213A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "MME 2273A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "MME 2285A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 5, courseCode: "SS 2143A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "MME 3325A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "BIOL 1001A" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "MME 3374A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "BME 3301A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "MME 3348A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 5, courseCode: "MME 3381A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "BIOL 1002B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "MME 3307A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "MME 3350A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "MME 3360A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "MME 3380A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 5, electiveLabel: "Non-technical elective" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "BIOCHEM 2280A" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "MME 3303A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "ECE 4455A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 3, courseCode: "PHYSIOL 2130" },
    { yearLevel: 4, term: "FALL", sortOrder: 4, electiveLabel: "Biomedical Science elective" },
    { yearLevel: 4, term: "FALL", sortOrder: 5, electiveLabel: "Healthcare non-technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "BME 3303A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "MME 4469A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, courseCode: "PHYSIOL 2130" },
    { yearLevel: 4, term: "WINTER", sortOrder: 3, electiveLabel: "Biomedical Science elective(s) (x2)" },
    { yearLevel: 4, term: "WINTER", sortOrder: 4, electiveLabel: "Healthcare non-technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 5, electiveLabel: "Open elective" },
    { yearLevel: 5, term: "FALL", sortOrder: 0, courseCode: "BME 4400E" },
    { yearLevel: 5, term: "FALL", sortOrder: 1, courseCode: "ELI 4110F/G" },
    { yearLevel: 5, term: "FALL", sortOrder: 2, courseCode: "MME 4499" },
    { yearLevel: 5, term: "FALL", sortOrder: 3, electiveLabel: "BME technical elective" },
    { yearLevel: 5, term: "FALL", sortOrder: 4, electiveLabel: "MME technical elective" },
    { yearLevel: 5, term: "WINTER", sortOrder: 0, courseCode: "BME 4400E" },
    {
      yearLevel: 5,
      term: "WINTER",
      sortOrder: 1,
      electiveLabel: "ELI 3000A/B, ELI 3100A/B, or ELI 4200A/B (or another approved elective, choose one)",
    },
    { yearLevel: 5, term: "WINTER", sortOrder: 2, courseCode: "MME 3334A/B" },
    { yearLevel: 5, term: "WINTER", sortOrder: 3, courseCode: "MME 4499" },
    { yearLevel: 5, term: "WINTER", sortOrder: 4, electiveLabel: "BME technical elective(s) (x2)" },
    { yearLevel: 5, term: "WINTER", sortOrder: 5, electiveLabel: "MME technical elective" },
  ],

  "mechatronics+biomedical": [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "MSE 2201A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "ECE 2205A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "MME 2202A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "MME 2204A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "CS 1037A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 6, courseCode: "BME 3201A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2276A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "MSE 2202A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "MSE 2233A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "MME 2213A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "MME 2273A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "MSE 3301A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "MSE 3310A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "ECE 3330A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "MME 3381A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "BIOL 1001A" },
    { yearLevel: 3, term: "FALL", sortOrder: 5, courseCode: "BME 3301A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "MSE 2221A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "MSE 3302A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "ECE 3331A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "MME 3360A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "MME 3380A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 5, courseCode: "BIOL 1002B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 6, electiveLabel: "Biomedical Science elective" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "BIOCHEM 2280A" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "ECE 2277A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "ECE 4455A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 3, courseCode: "PHYSIOL 2130" },
    { yearLevel: 4, term: "FALL", sortOrder: 4, courseCode: "SS 2141A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 5, electiveLabel: "Biomedical Science elective" },
    { yearLevel: 4, term: "FALL", sortOrder: 6, electiveLabel: "Healthcare non-technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "BME 3303A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "ECE 3375A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, courseCode: "MME 4469A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 3, courseCode: "PHYSIOL 2130" },
    { yearLevel: 4, term: "WINTER", sortOrder: 4, electiveLabel: "Biomedical Science elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 5, electiveLabel: "Healthcare non-technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 6, electiveLabel: "BME technical elective" },
    { yearLevel: 5, term: "FALL", sortOrder: 0, courseCode: "MSE 4401A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 1, courseCode: "MSE 4499" },
    { yearLevel: 5, term: "FALL", sortOrder: 2, courseCode: "BME 4400E" },
    { yearLevel: 5, term: "FALL", sortOrder: 3, courseCode: "ECE 4445A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 4, courseCode: "ELI 4110F/G" },
    { yearLevel: 5, term: "FALL", sortOrder: 5, electiveLabel: "Healthcare non-technical elective" },
    { yearLevel: 5, term: "WINTER", sortOrder: 0, courseCode: "MSE 4499" },
    { yearLevel: 5, term: "WINTER", sortOrder: 1, electiveLabel: "ECE 4460A/B or ECE 4469A/B (choose one)" },
    { yearLevel: 5, term: "WINTER", sortOrder: 2, courseCode: "BME 4400E" },
    {
      yearLevel: 5,
      term: "WINTER",
      sortOrder: 3,
      electiveLabel: "ELI 3000A/B, ELI 3100A/B, or ELI 4200A/B (or another approved elective, choose one)",
    },
    { yearLevel: 5, term: "WINTER", sortOrder: 4, electiveLabel: "BME technical elective(s) (x2)" },
  ],

  "chemical+biomedical": [
    { yearLevel: 2, term: "FALL", sortOrder: 0, courseCode: "NMM 2270A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 1, courseCode: "BME 3201A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 2, courseCode: "CBE 2206A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 3, courseCode: "CBE 2214A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 4, courseCode: "CBE 2220A/B" },
    { yearLevel: 2, term: "FALL", sortOrder: 5, courseCode: "CBE 2290A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 0, courseCode: "NMM 2277A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 1, courseCode: "CBE 2207A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 2, courseCode: "CBE 2221A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 3, courseCode: "CBE 2224A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 4, courseCode: "CBE 2291A/B" },
    { yearLevel: 2, term: "WINTER", sortOrder: 5, courseCode: "SS 2143A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 0, courseCode: "BIOL 1001A" },
    { yearLevel: 3, term: "FALL", sortOrder: 1, courseCode: "CBE 3307A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 2, courseCode: "CBE 3315A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 3, courseCode: "CBE 3322A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 4, courseCode: "CBE 3395Y" },
    { yearLevel: 3, term: "FALL", sortOrder: 5, courseCode: "BME 3301A/B" },
    { yearLevel: 3, term: "FALL", sortOrder: 6, electiveLabel: "Non-technical elective" },
    { yearLevel: 3, term: "WINTER", sortOrder: 0, courseCode: "BIOL 1002B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 1, courseCode: "CBE 3310A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 2, courseCode: "CBE 3324A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 3, courseCode: "CBE 3319A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 4, courseCode: "CBE 3323A/B" },
    { yearLevel: 3, term: "WINTER", sortOrder: 5, courseCode: "CBE 3316A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 0, courseCode: "BIOCHEM 2280A" },
    { yearLevel: 4, term: "FALL", sortOrder: 1, courseCode: "ECE 4455A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 2, courseCode: "PHYSIOL 2130" },
    { yearLevel: 4, term: "FALL", sortOrder: 3, courseCode: "CBE 3318A/B" },
    { yearLevel: 4, term: "FALL", sortOrder: 4, electiveLabel: "Biomedical Science elective" },
    { yearLevel: 4, term: "FALL", sortOrder: 5, electiveLabel: "Healthcare non-technical elective(s) (x2)" },
    { yearLevel: 4, term: "WINTER", sortOrder: 0, courseCode: "BME 3303A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 1, courseCode: "MME 4469A/B" },
    { yearLevel: 4, term: "WINTER", sortOrder: 2, courseCode: "PHYSIOL 2130" },
    { yearLevel: 4, term: "WINTER", sortOrder: 3, electiveLabel: "Biomedical Science elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 4, electiveLabel: "BME technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 5, electiveLabel: "Healthcare non-technical elective" },
    { yearLevel: 4, term: "WINTER", sortOrder: 6, electiveLabel: "Open elective" },
    { yearLevel: 5, term: "FALL", sortOrder: 0, courseCode: "BME 4400E" },
    { yearLevel: 5, term: "FALL", sortOrder: 1, courseCode: "CBE 4421A/B" },
    { yearLevel: 5, term: "FALL", sortOrder: 2, courseCode: "CBE 4497" },
    { yearLevel: 5, term: "FALL", sortOrder: 3, courseCode: "ELI 4110F/G" },
    {
      yearLevel: 5,
      term: "FALL",
      sortOrder: 4,
      electiveLabel: "ELI 3000A/B, ELI 3100A/B, or ELI 4200A/B (or another approved elective, choose one)",
    },
    { yearLevel: 5, term: "FALL", sortOrder: 5, electiveLabel: "CBE technical elective" },
    { yearLevel: 5, term: "WINTER", sortOrder: 0, courseCode: "BME 4400E" },
    { yearLevel: 5, term: "WINTER", sortOrder: 1, courseCode: "CBE 4497" },
    {
      yearLevel: 5,
      term: "WINTER",
      sortOrder: 2,
      electiveLabel: "ELI 3000A/B, ELI 3100A/B, or ELI 4200A/B (or another approved elective, choose one)",
    },
    { yearLevel: 5, term: "WINTER", sortOrder: 3, electiveLabel: "BME technical elective(s) (x2)" },
    { yearLevel: 5, term: "WINTER", sortOrder: 4, electiveLabel: "CBE technical elective" },
  ],
};
