import type { Term } from "../../app/generated/prisma/client";

export type UpperYearCourse = {
  code: string;
  title: string;
  description: string;
  yearLevel: number;
  termsOffered: Term[];
  isCore: boolean;
  prerequisites: string;
  antirequisites: string;
};

/**
 * Real, verified upper-year courses per discipline, sourced from the
 * Western Academic Calendar (westerncalendar.uwo.ca) and eng.uwo.ca
 * department pages. Ratings/reviews are synthetic — course codes, titles,
 * prerequisites, and antirequisites are not: prerequisites/antirequisites
 * are pulled verbatim from the live calendar as of 2026-08.
 *
 * Two corrections from the original program list, confirmed against the
 * live calendar:
 * - "Computer Engineering" was discontinued as a standalone Western degree
 *   in September 2022. Its courses are folded into Electrical Engineering
 *   below (ECE now serves both) rather than seeded as a separate program.
 * - Integrated Engineering's upper-year prefix is `IE`, not `ES` — `ES` is
 *   only used for the four first-year common courses.
 *
 * Integrated Engineering has fewer dedicated courses than the other core
 * disciplines (11) — that's a real, small-catalogue program, not a
 * seeding shortcut.
 *
 * Green Process Engineering has been removed entirely (see DISCIPLINES in
 * seed.ts) — it's confirmed discontinued as a standalone program, not just
 * renamed course codes.
 *
 * `aise` and `biomedical` are combined/concurrent degrees (Discipline.
 * isCombinedDegree = true in seed.ts) — students take these alongside a
 * core discipline, and only their own dedicated courses (confirmed on the
 * live calendar under the AISE/BME subjects) are seeded here, not the
 * shared core-discipline courses they also take.
 */
export const UPPER_YEAR_COURSES: Record<string, UpperYearCourse[]> = {
  chemical: [
    { code: "CBE 2220A/B", title: "Chemical Process Calculations", description: "Material and energy balances that underpin every later chemical engineering course.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "NMM 1411A/B, NMM 1414A/B, Chemistry 1302A/B, Physics 1401A/B or 1201A/B, Physics 1402A/B or 1202A/B.", antirequisites: "None." },
    { code: "CBE 2221A/B", title: "Fluid Flow", description: "Momentum transfer, conservation laws, and flow measurement for process fluids.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "NMM 1414A/B or the former Applied Mathematics 1414A/B.", antirequisites: "None." },
    { code: "CBE 2224A/B", title: "Chemical Engineering Thermodynamics", description: "Phase equilibria, solution behaviour, and reaction equilibria in separation processes.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "CBE 2214A/B or MME 2204A/B; NMM 1414A/B or the former Applied Mathematics 1414A/B.", antirequisites: "None." },
    { code: "CBE 2290A/B", title: "Fundamentals of Biochemical and Environmental Engineering", description: "Microbiology and biochemistry applied to environmental engineering problems.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Chemistry 1302A/B or the former Chemistry 1024A/B.", antirequisites: "None." },
    { code: "CBE 3310A/B", title: "Process Dynamics and Control", description: "Dynamic behaviour and control of chemical processes, with MATLAB/Simulink.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "NMM 2277A/B or the former Applied Mathematics 2277A/B, or NMM 2276A/B or the former Applied Mathematics 2276A/B; CBE 2291A/B.", antirequisites: "The former CBE 4410A/B." },
    { code: "CBE 3315A/B", title: "Reaction Engineering", description: "Chemical kinetics and the reactor design math that follows from it.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "NMM 1414A/B or the former Applied Mathematics 1414A/B; CBE 2224A/B; Chemistry 1302A/B.", antirequisites: "None." },
    { code: "CBE 3322A/B", title: "Heat Transfer Operations", description: "Conduction, convection, and radiation, applied to heat exchanger design.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "CBE 2220A/B; CBE 2221A/B or registration in the Integrated Engineering program.", antirequisites: "None." },
    { code: "CBE 3324A/B", title: "Mass Transfer Operations", description: "Absorption, stripping, humidification, and drying equipment design.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "CBE 2220A/B; CBE 2221A/B.", antirequisites: "None." },
    { code: "CBE 4409A/B", title: "Wastewater Treatment", description: "Municipal wastewater processes, regulation, and treatment plant design.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "CBE 2290A/B or CEE 2217A/B or Chemistry 2210A/B.", antirequisites: "The former CBE 3363A/B." },
    { code: "CBE 4417A/B", title: "Principles and Applications of Heterogeneous Catalysis", description: "Kinetics and mechanisms behind industrially catalyzed reactions.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "CBE 3315A/B or the former GPE 3315A/B; CBE 2206A/B or the former GPE 2213A/B.", antirequisites: "None." },
    { code: "CBE 4497", title: "Chemical Process & Plant Design", description: "Capstone full-scale process design, covering equipment and cost analysis.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "CBE 2220A/B; CBE 2224A/B; CBE 3315A/B; CBE 3322A/B; CBE 3323A/B; CBE 3324A/B; CBE 3318A/B; CBE 3319A/B.", antirequisites: "CBE 4498; CEE 4441; ECE 4416; MME 4499; SE 4450; ES 4499; MSE 4499; ECE 4415; the former GPE 4497." },
    { code: "CBE 4498", title: "Biochemical Process and Plant Design", description: "Capstone design project for biochemical process plants.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "CBE 3315A/B; CBE 3318A/B; CBE 3319A/B; CBE 3322A/B; CBE 3323A/B; CBE 3324A/B; CBE 3330A/B.", antirequisites: "CBE 4497; CEE 4441; ECE 4415; ECE 4416; ES 4499; MME 4499; MSE 4499; SE 4450; the former GPE 4497." },
  ],
  civil: [
    { code: "CEE 2202A/B", title: "Mechanics of Materials", description: "Stress, strain, torsion, and beam bending — the core toolkit for structural analysis.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Engineering Science 1022A/B/Y; NMM 1412A/B or the former Applied Mathematics 1412A/B.", antirequisites: "MME 2202A/B." },
    { code: "CEE 2217A/B", title: "Introduction to Environmental Engineering", description: "Mass and energy transfer, environmental chemistry, and pollution management.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Chemistry 1302A/B or the former Chemistry 1024A/B.", antirequisites: "Chemistry 2210A/B." },
    { code: "CEE 2225A/B", title: "Fundamentals of Fluid Mechanics", description: "Fluid statics and the continuity, momentum, and energy equations.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Engineering Science 1022A/B/Y; Physics 1401A/B. Corequisite: NMM 2270A/B.", antirequisites: "CBE 2221A/B; MME 2273A/B; the former CEE 2224." },
    { code: "CEE 3324A/B", title: "Surveying", description: "Plane surveying theory alongside AutoCAD for civil drawings.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Enrolled in Civil Engineering.", antirequisites: "None." },
    { code: "CEE 3340A/B", title: "Analysis of Indeterminate Structures", description: "Frames, continuous beams, and arches, by hand and by computer.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "CEE 2221A/B.", antirequisites: "None." },
    { code: "CEE 3346A/B", title: "Steel Design", description: "Tension members, columns, beams, and connections under Limit States Design.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "CEE 3340A/B.", antirequisites: "None." },
    { code: "CEE 3347A/B", title: "Reinforced Concrete Design", description: "Serviceability and ultimate limit states for beams, slabs, and columns.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "CEE 2202A/B; CEE 2221A/B.", antirequisites: "None." },
    { code: "CEE 3361A/B", title: "Water Resources Management", description: "Regulatory, economic, sustainability, and climate-change dimensions of water systems.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "CEE 2219A/B. Corequisite: Earth Sciences 3340A/B.", antirequisites: "None." },
    { code: "CEE 4401A/B", title: "Principles of Transportation Engineering", description: "Vehicle motion, geometric design, traffic modelling, and planning.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "CEE 2219A/B.", antirequisites: "None." },
    { code: "CEE 4426A/B", title: "Geotechnical Engineering Design", description: "Site investigation, shallow and deep foundations, and retaining structures.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "CEE 3322A/B.", antirequisites: "None." },
    { code: "CEE 4440", title: "Civil Engineering Thesis", description: "Individual research thesis, presented publicly at year's end.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Completion of third year of the Civil Engineering program.", antirequisites: "None." },
    { code: "CEE 4441", title: "Civil Engineering Design Project", description: "Capstone team design project.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Completion of third year of the Civil Engineering program.", antirequisites: "CBE 4497; ECE 4416; MME 4499; SE 4450; ES 4499." },
  ],
  electrical: [
    { code: "ECE 2205A/B", title: "Electric Circuits", description: "Ohm's and Kirchhoff's Laws, nodal/mesh analysis, and network theorems.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Physics 1202A/B or the former Physics 1302A/B or Physics 1402A/B; NMM 1411A/B or the former Applied Mathematics 1411A/B; NMM 1412A/B or the former Applied Mathematics 1412A/B; Engineering Science 1036A/B or Computer Science 1026A/B. Corequisite: NMM 2270A/B.", antirequisites: "None." },
    { code: "ECE 2236A/B", title: "Magnetic Circuits & Transmission Lines", description: "Three-phase circuits, transformers, and the telegrapher equations.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "NMM 2270A/B or the former Applied Mathematics 2270A/B; ECE 2205A/B; Physics 1202A/B or the former Physics 1302A/B or Physics 1402A/B. Corequisite: NMM 2276A/B.", antirequisites: "None." },
    { code: "ECE 2277A/B", title: "Digital Logic Systems", description: "Boolean algebra, Karnaugh maps, and the logic/memory systems built from them.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Physics 1202A/B or the former Physics 1302A/B or Physics 1402A/B. Corequisite: ECE 2205A/B or registration in the Integrated Engineering or Software Engineering program.", antirequisites: "The former ECE 3339A/B." },
    { code: "ECE 3332A/B", title: "Electric Machines", description: "Magnetic fields, transformers, and DC/synchronous/induction machines.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "ECE 2233A/B and ECE 2236A/B.", antirequisites: "None." },
    { code: "ECE 3333A/B", title: "Electric Power Systems I", description: "The per-unit system, three-phase transmission, and power flow.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "ECE 2236A/B; ECE 3332A/B.", antirequisites: "None." },
    { code: "ECE 3336A/B", title: "Electromagnetic Theory", description: "RF transmission lines, the Smith chart, and Maxwell's equations.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "NMM 2276A/B or the former Applied Mathematics 2276A/B; NMM 3415A/B or the former Applied Mathematics 3415A/B; ECE 2233A/B; ECE 2236A/B.", antirequisites: "Physics 3300A/B." },
    { code: "ECE 3349A/B", title: "Introduction of VLSI", description: "Semiconductor physics and CMOS circuit design.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Engineering Science 1021A/B; ECE 2233A/B, ECE 2240A/B, ECE 2231A/B, ECE 2277A/B or ES 1021A/B, ECE 2238A/B, ECE 2277A/B; and successful completion of second year.", antirequisites: "None." },
    { code: "ECE 3375A/B", title: "Microprocessors & Microcomputers", description: "CPUs, memory, and I/O interfacing for real microprocessor applications.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "ECE 2277A/B or the former ECE 3339A/B.", antirequisites: "Computer Science 3350A/B." },
    { code: "ECE 3389A/B", title: "Computer System Design", description: "Computer architecture, memory hierarchy, and RISC/multi-core design.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "ECE 3375A/B and ECE 3380A/B, or completion of third year of the Software Engineering program.", antirequisites: "The former ECE 4470A/B; the former ECE 4489A/B." },
    { code: "ECE 4436A/B", title: "Networking: Principles, Protocols and Architecture", description: "The OSI/TCP-IP models, packet switching, and routing.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Engineering Science 1036A/B or Computer Science 1026A/B.", antirequisites: "Computer Science 3357A/B; AISE 4430A/B; the former SE 4430A/B." },
    { code: "ECE 4457A/B", title: "Power Electronics", description: "Power semiconductor devices and converter topologies.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "ECE 2233A/B and ECE 3333A/B.", antirequisites: "None." },
    { code: "ECE 4460A/B", title: "Real-Time and Embedded Systems", description: "Real-time kernels, multi-tasking, and schedulability analysis.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "(Computer Science 1027A/B or Computer Science 1037A/B or SE 2205A/B or AISE 2205A/B) and ECE 3375A/B.", antirequisites: "None." },
    { code: "ECE 4464A/B", title: "Electric Power Systems II", description: "Power flow, faults, stability, and HVDC/FACTS.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "ECE 3333A/B.", antirequisites: "None." },
    { code: "ECE 4416", title: "Electrical/Computer Design Project", description: "Capstone design project.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Completion of third year of the Electrical, Computer, or Integrated Engineering programs.", antirequisites: "CBE 4497; CEE 4441; MME 4499; SE 4450; Engineering Science 4499." },
  ],
  aise: [
    { code: "AISE 2205A/B", title: "Algorithms & Data Structures for Object-Oriented Design", description: "Algorithms and data structures, taught through the AISE program's own section.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Computer Science 1026A/B or Engineering Science 1036A/B.", antirequisites: "Computer Science 2210A/B; SE 2205A/B." },
    { code: "AISE 2251A/B", title: "Software Design for Systems Engineering", description: "Object-oriented and systems-level software design for AI/ML pipelines.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "AISE 2205A/B (or SE 2205A/B pre-2024-25); Engineering Science 1036A/B or Computer Science 1026A/B.", antirequisites: "Computer Science 2212A/B/Y; SE 2203A/B; the former SE 2251A/B." },
    { code: "AISE 3010A/B", title: "Data Engineering and Machine Learning", description: "Building data pipelines and applying core machine learning methods to them.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "AISE 2205A/B (or SE 2205A/B); AISE 2251A/B (or SE 2203A/B); AISE 3309A/B (or SE 3309A/B); DS 3000A/B.", antirequisites: "None." },
    { code: "AISE 3020A/B", title: "AI: Ethics, Bias and Privacy", description: "The ethical, legal, and social dimensions of deploying AI systems.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "DS 3000A/B.", antirequisites: "None." },
    { code: "AISE 3309A/B", title: "Database Management Systems", description: "Relational databases and query languages, taught through the AISE program's own section.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "AISE 2205A/B (or SE 2205A/B pre-2024-25); AISE 2251A/B (or the former SE 2251A/B).", antirequisites: "Computer Science 3319A/B; Computer Science 3120A/B; SE 3309A/B." },
    { code: "AISE 3350A/B", title: "Cyber-Physical Systems Theory", description: "The mathematical foundations connecting physical systems to their digital controllers.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "NMM 2270A/B; NMM 2276A/B or 2277A/B; Physics 1302A/B or 1402A/B.", antirequisites: "The former ECE 3350A/B." },
    { code: "AISE 3351A/B", title: "Digital Systems and Signal Processing", description: "Sampling, filtering, and digital signal processing for cyber-physical systems.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "AISE 3350A/B or the former ECE 3350A/B (pre-2024-25).", antirequisites: "ECE 3331A/B; the former ECE 3351A/B." },
    { code: "AISE 4010A/B", title: "Deep Learning for Time Series Data", description: "Neural network architectures applied to sequential and time-series data.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "DS 3000A/B; AISE 3010A/B.", antirequisites: "None." },
    { code: "AISE 4020A/B", title: "AI Systems Engineering Design I", description: "First half of the AISE capstone: scoping and prototyping an AI-driven system.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "DS 3000A/B; AISE 3010A/B.", antirequisites: "None." },
    { code: "AISE 4025A/B", title: "Introduction to Computer Assisted Surgery: Theory and Practice", description: "AI and signal-processing methods applied to surgical guidance systems.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "(Engineering Science 1036A/B or Computer Science 1025A/B or 1026A/B) and (NMM 2276A/B or 2277A/B) and ECE 4445A/B.", antirequisites: "None." },
    { code: "AISE 4030A/B", title: "Reinforcement Learning", description: "Sequential decision-making methods, from bandits through deep RL.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "DS 3000A/B and (NMM 2276A/B or 2277A/B).", antirequisites: "None." },
    { code: "AISE 4050", title: "AI Systems Engineering Design II", description: "Capstone continuation: build and deliver the AI system designed in AISE 4020A/B.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Completion of fourth year of the AISE program.", antirequisites: "CBE 4497; CEE 4441; ECE 4416; MME 4499; ES 4499." },
    { code: "AISE 4430A/B", title: "Introduction to Computer Networking, Security & IoT Systems", description: "Networking, security, and IoT fundamentals for connected AI systems.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "AISE 2205A/B (or SE 2205A/B pre-2024-25); Engineering Science 1036A/B.", antirequisites: "Computer Science 3357A/B; ECE 4436A/B; the former SE 4430A/B." },
    { code: "AISE 4450A/B", title: "Data Driven Control of Cyber-Physical Systems", description: "Learning-based control methods for cyber-physical and robotic systems.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "AISE 3010A/B; AISE 3351A/B (or the former ECE 3351A/B); DS 3000A/B.", antirequisites: "The former ECE 4450A/B." },
    { code: "AISE 4470A/B", title: "Selected Topics in AI Systems Engineering I", description: "Rotating special-topics course in AI systems engineering.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Completion of third year of the AISE program.", antirequisites: "None." },
    { code: "AISE 4471A/B", title: "Selected Topics in AI Systems Engineering II", description: "Rotating special-topics course in AI systems engineering, continued.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Completion of fourth year of the AISE program.", antirequisites: "None." },
  ],
  biomedical: [
    { code: "BME 3201A/B", title: "Fundamentals of Biomedical Engineering Design", description: "Design skills and tools for medical devices, with a focus on cardiovascular and musculoskeletal systems.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Completion of the first-year Faculty of Engineering curriculum with a minimum 80% average.", antirequisites: "MME 4470A/B." },
    { code: "BME 3301A/B", title: "Neural Systems Engineering", description: "Neurophysiology and neural modelling — EEG, EMG, fMRI, brain-computer interfaces, and neural prosthetics.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "BME 3201A/B.", antirequisites: "None." },
    { code: "BME 3303A/B", title: "Cellular Systems Engineering", description: "Engineering design and mathematical models applied to cellular and molecular biology.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "BME 3201A/B; Biology 1002B (or the former 1202B); Biochemistry 2280A.", antirequisites: "None." },
    { code: "BME 4400E", title: "BME Research Project", description: "Independent research project with faculty supervision, including research ethics and two presentations.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Registration in the final year of the Biomedical Engineering program.", antirequisites: "CBE 4415; CBE 4425; MME 4410." },
  ],
  integrated: [
    { code: "IE 2200Y", title: "Practical Elements in Integrated Engineering", description: "Hands-on practice of the technical and software skills used across design projects.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Registration in the Integrated Engineering program.", antirequisites: "None." },
    { code: "IE 2298", title: "Integrated Systems Engineering and Design", description: "The systems engineering V-model and human-centred, sustainability-aware design.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Registration in Integrated Engineering.", antirequisites: "MME 2259A/B; the former Integrated Engineering 2297A/B." },
    { code: "IE 2299A/B", title: "Integrated Systems and Design", description: "Systems engineering approaches drawn from multiple disciplinary frameworks.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Registration in Year 2 or higher in Engineering.", antirequisites: "IE 2298; the former IE 2297A/B." },
    { code: "IE 2399A/B", title: "Systems Engineering Project", description: "Applied systems engineering methods through a multidisciplinary project.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "IE 2299A/B.", antirequisites: "IE 2298." },
    { code: "IE 4490A/B", title: "Integrated Engineering Undergraduate Research", description: "Independent research under faculty supervision.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Permission of instructor and a minimum cumulative grade average of 75% at time of registration.", antirequisites: "None." },
    { code: "IE 4491A/B", title: "Integrated Engineering Undergraduate Research", description: "Continuation of IE 4490's independent research.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "IE 4490A/B.", antirequisites: "None." },
    { code: "IE 4499", title: "Interdisciplinary Engineering Design Project", description: "Capstone team design project spanning multiple engineering disciplines.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Completion of Year III of the Integrated Engineering program.", antirequisites: "CBE 4497; CEE 4441; ECE 4416; MME 4499; MSE 4499; SE 4450." },
    { code: "ELI 3000A/B", title: "Managing the Innovation Process", description: "How organizations move ideas from concept to commercialized product.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Enrollment in Year 2 or above in Engineering.", antirequisites: "None." },
    { code: "ELI 3100A/B", title: "Planning and Project Management", description: "Project planning, scheduling, and management tools for engineering teams.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Completion of second year in any Engineering program.", antirequisites: "CEE 3348A/B." },
    { code: "ELI 4100F/G", title: "Engineering Leadership", description: "Leadership theory and practice framed around engineering teams and projects.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Enrollment in Year 3 or above in Engineering.", antirequisites: "The former Engineering Science 4480A/B." },
    { code: "ELI 4200A/B", title: "The Entrepreneurial Environment", description: "What it actually takes to start and grow a venture, from an engineer's seat.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Completion of Year 2 Engineering, or enrollment in Year 2 Software Engineering.", antirequisites: "Business Administration 3300K; the former Engineering Science 4481A/B." },
  ],
  mechanical: [
    { code: "MME 2202A/B", title: "Mechanics of Materials", description: "Stress, strain, Mohr's circle, torsion, and beam bending.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Engineering Science 1022A/B/Y; NMM 1412A/B.", antirequisites: "CEE 2202A/B; the former MSE 2212A/B." },
    // Also runs in Summer (confirmed on Western's official Summer Academic
    // Timetable as MME 2204A) alongside its normal Fall/Winter offering.
    { code: "MME 2204A/B", title: "Thermodynamics I", description: "The first and second laws, ideal gases, and energy conversion systems.", yearLevel: 2, termsOffered: ["FALL", "WINTER", "SUMMER"], isCore: true, prerequisites: "NMM 1414A/B.", antirequisites: "CBE 2214A/B; the former MSE 2214A/B." },
    { code: "MME 2213A/B", title: "Engineering Dynamics", description: "Rectilinear, angular, and curvilinear motion for particles and rigid bodies.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Engineering Science 1022A/B/Y.", antirequisites: "MSE 2213A/B." },
    { code: "MME 2259A/B", title: "Product Design & Development", description: "The mechanical design process, DFMA, and concept generation.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Engineering Science 1021A/B; Engineering Science 1022A/B/Y; Engineering Science 1050.", antirequisites: "None." },
    { code: "MME 3303A/B", title: "Fluid Mechanics II", description: "Rigid-body motion, control volume analysis, and centrifugal pumps.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "MME 2273A/B.", antirequisites: "None." },
    { code: "MME 3325A/B", title: "Mechanical Vibrations", description: "Single and multi-degree-of-freedom systems, damping, and modal analysis.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "NMM 2270A/B.", antirequisites: "MME 4425A/B." },
    { code: "MME 3348A/B", title: "Manufacturing Processes", description: "Industrial manufacturing processes and how they shape material performance.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Engineering Science 1021A/B; MME 2202A/B or CEE 2202A/B; MME 2260A/B.", antirequisites: "None." },
    { code: "MME 3380A/B", title: "Mechanical Components Design", description: "Stress analysis and design of standard machine components.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "MME 2200Q/R/S/T or MSE 2200Q/R/S/T; MME 2202A/B or MSE 2212A/B; MME 3381A/B or MSE 3381A/B.", antirequisites: "The former MSE 3380A/B." },
    { code: "MME 4423A/B", title: "Internal Combustion Engines", description: "Spark-ignition and diesel engine design and performance.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "MME 3334A/B.", antirequisites: "None." },
    { code: "MME 4452A/B", title: "Robotics & Manufacturing Automation", description: "Sensors, actuators, industrial robots, and machine vision.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "MME 3374A/B, MME 3380A/B, or ECE 3330A/B and ECE 3375A/B, or registration in fourth year of the Integrated Engineering program.", antirequisites: "None." },
    { code: "MME 4410", title: "Mechanical & Materials Engineering Thesis", description: "Individual thesis research, presented publicly at year's end.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "Completion of the third year of the Mechanical Engineering or Mechatronic Systems Engineering program with a minimum 80% average.", antirequisites: "None." },
    { code: "MME 4499", title: "Mechanical Engineering Design Project", description: "Capstone team design project.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Completion of the third year of the Mechanical Engineering program.", antirequisites: "CBE 4497; CEE 4441; ECE 4416; SE 4450; ES 4499." },
  ],
  mechatronics: [
    { code: "MSE 2201A/B", title: "Introduction to Electrical Instrumentation", description: "Instrumentation basics, electronics, and signal conditioning.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "None.", antirequisites: "ECE 2240A/B." },
    { code: "MSE 2202A/B", title: "Intro to Mechatronic Design", description: "Structured design methods for mechatronic systems.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Engineering Science 1021A/B; Engineering Science 1022A/B/Y; Engineering Science 1050; MSE 2200Q/R/S/T.", antirequisites: "None." },
    { code: "MSE 2221A/B", title: "Computational Methods for Mechatronic Systems Engineers", description: "Numerical methods and their programming applications.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Engineering Science 1036A/B; NMM 1411A/B; NMM 1414A/B.", antirequisites: "MME 2221A/B; CEE 2219A/B; CBE 2291A/B." },
    { code: "MSE 2233A/B", title: "Circuits and Systems", description: "The s-plane, frequency response, and Laplace transforms.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "NMM 2270A/B; ECE 2205A/B.", antirequisites: "ECE 2233A/B." },
    { code: "MSE 3301A/B", title: "Materials Selection and Manufacturing Processes", description: "Choosing materials for mechatronic components, including smart materials.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "MSE 2202A/B or Integrated Engineering 2298.", antirequisites: "MME 3379A/B." },
    { code: "MSE 3302A/B", title: "Sensors & Actuators", description: "Traditional sensors, MEMS sensing, and smart materials.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "MSE 2202A/B; MSE 3310A/B; ECE 3330A/B.", antirequisites: "None." },
    { code: "MSE 3310A/B", title: "Electric Motors and Drives", description: "DC/AC motor operation and power electronics integration.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "MSE 2201A/B; MSE 2233A/B.", antirequisites: "ECE 3332A/B; ECE 4457A/B." },
    { code: "MSE 4401A/B", title: "Robotic Manipulators", description: "Kinematics, dynamics, and control of rigid-link manipulators.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "MSE 3302A/B.", antirequisites: "None." },
    { code: "MSE 4499", title: "Mechatronic Design Project", description: "Interdisciplinary capstone design project.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "MSE 3302A/B; MSE 3380A/B or MME 3380A/B.", antirequisites: "CBE 4497; MME 4419; CEE 4441; the former GPE 4497; SE 4450; MME 4499; ECE 4415; ECE 4416; Engineering Science 4499." },
  ],
  software: [
    { code: "SE 2202A/B", title: "Scripting Programming Language Fundamentals", description: "JavaScript scripting alongside HTML/CSS basics.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Engineering Science 1036A/B.", antirequisites: "Computer Science 1046A/B." },
    { code: "SE 2203A/B", title: "Software Design", description: "Object-oriented design and UML for real-time and distributed systems.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Computer Science 1026A/B or Engineering Science 1036A/B.", antirequisites: "None." },
    { code: "SE 2205A/B", title: "Algorithms & Data Structure for Object-Oriented Design", description: "Algorithms and data structures, with an eye on performance at scale.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Computer Science 1026A/B or Engineering Science 1036A/B.", antirequisites: "AISE 2205A/B; Computer Science 2210A/B." },
    { code: "SE 2250A/B", title: "Software Construction", description: "Implementation, testing, tooling, debugging, and change management.", yearLevel: 2, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Computer Science 1026A/B or Engineering Science 1036A/B.", antirequisites: "None." },
    { code: "SE 3309A/B", title: "Database Management Systems", description: "Relational databases, entity-relationship modelling, and query languages.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "SE 2203A/B; SE 2205A/B.", antirequisites: "AISE 3309A/B; Computer Science 3319A/B; Computer Science 3120A/B." },
    { code: "SE 3313A/B", title: "Operating Systems for Software Engineering", description: "OS theory and construction, including real-time and embedded systems.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "SE 2203A/B; SE 2205A/B or Computer Science 2210A/B.", antirequisites: "Computer Science 3305A/B." },
    { code: "SE 3350A/B", title: "Software Engineering Design I", description: "A large group project run like professional practice.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "SE 2203A/B; SE 3352A/B; SE 3351A/B. Corequisite: SE 3353A/B.", antirequisites: "Computer Science 3307A/B/Y." },
    { code: "SE 3352A/B", title: "Software Requirements and Analysis", description: "Feasibility studies and requirements elicitation and validation.", yearLevel: 3, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "(SE 2203A/B and SE 2205A/B) or (Computer Science 2210A/B and CS 2212A/B/Y).", antirequisites: "Computer Science 4473A/B." },
    { code: "SE 4450", title: "Software Engineering Design II", description: "Capstone large-scale software project.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: true, prerequisites: "Completion of third year of the SE program. Corequisite: SE 4452A/B, SE 4455A/B.", antirequisites: "CBE 4497; CEE 4441; ECE 4416; MME 4499; Engineering Science 4499." },
    { code: "SE 4452A/B", title: "Software Testing & Maintenance", description: "Testing techniques, verification, validation, and maintenance.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "SE 3352A/B.", antirequisites: "Computer Science 4472A/B." },
    { code: "SE 4455A/B", title: "Cloud Computing: Concepts, Technologies and Applications", description: "Virtualization and distributed systems, with hands-on VM labs.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "(ECE 4436A/B or AISE 4430A/B or the former SE 4430A/B, SE 3313A/B, SE 3314A/B) or (CS 3357A/B, CS 3305A/B).", antirequisites: "None." },
    { code: "SE 4472A/B", title: "Information Security", description: "Network security and protecting information systems.", yearLevel: 4, termsOffered: ["FALL", "WINTER"], isCore: false, prerequisites: "ECE 4436A/B or Computer Science 3357A/B; SE 3313A/B or CS 3305A/B.", antirequisites: "None." },
  ],
};
